
language: ruby

cache: bundler 

before_install: 
  - gem update bundler
  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb
install:
  - bundle install
  
script:
  - bundle exec jekyll build
  - make
  
branches:
  only:
  - gh-pages

sudo: false
