stages: deploy


pages:
  stage: deploy
  image: schickling/latex
  script:
    - mkdir public
    - xelatex -output-directory public resume.tex
  artifacts:
    paths:
      - public
  only:
    - master
