sudo:       required
language:   generic
services:   docker

# Docs of the options: https://github.com/moya10/awesome-cv/tree/master#configuration-options
tex-config:
- tex-scheme=small
- push-type=none
- build-pattern=resume.tex
#- latexmk-flags=-dvi -f
# Check at https://www.ctan.org/pkg/package-name in which TeX Live package a LaTeX package is contained.
- packages=xkeyval, geometry,hyphenat,csquotes,tocloft,xltxtra,sectsty,ulem,marginnote,fontawesome5,nowidow,microtype,hyperref,academicons, xunicode,multicol, fontspec,xgreek,polyglossia,collection-latex, collection-langeuropean, exam, amsmath, amscls, mathtools, thmtools, stmaryrd, xcolor, pdfpages, pgf, cancel, hyperref, pgfplots, listings, scalerel, stackengine, etoolbox, listofitems, marvosym, amsfonts, opensans, slantsc, fancyhdr, ulem, algorithms, algorithmicx, float, booktabs, enumitem, polynom, fancyvrb, makecmds, multirow, chngcntr, fvextra, upquote, lineno, ifplatform, xstring, framed, caption, collection-fontsrecommended, minted, pgfgantt, geometry, beamer, translator, environ, trimspaces, imakeidx, graphics, tools, oberdiek

# We will use the docker image from https://hub.docker.com/r/phpirates/texlive-latexbuild/
script:
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind phpirates/texlive-latexbuild:small-2018
